# Valori per Prometheus
prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: NodePort
    persistentVolume:
      enabled: false

# Valori per Grafana
grafana:
  adminPassword: "admin"  # Password admin per Grafana
  service:
    type: NodePort       # Usa NodePort per rendere accessibile Grafana
  ingress:
    enabled: false       # Non useremo ingress per ora
  persistence:
    enabled: false       # Non persisteremo i dati
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true
  dashboards:
    default:
      my-dashboard:
        json: |
          {
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": "-- Grafana --",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
                }
              ]
            },
            "panels": [],
            "title": "My Dashboard",
            "version": 1
          }
